/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResidentAccountRouteImport } from './routes/resident-account'
import { Route as ResidentRouteImport } from './routes/resident'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArtisanAccountRouteImport } from './routes/artisan-account'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ApiContractsRouteImport } from './routes/api-contracts'
import { Route as AdminConsoleRouteImport } from './routes/admin-console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtisanIndexRouteImport } from './routes/artisan.index'
import { Route as RequestIdRouteImport } from './routes/request.$id'
import { Route as ArtisanIdRouteImport } from './routes/artisan.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentAccountRoute = ResidentAccountRouteImport.update({
  id: '/resident-account',
  path: '/resident-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentRoute = ResidentRouteImport.update({
  id: '/resident',
  path: '/resident',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanAccountRoute = ArtisanAccountRouteImport.update({
  id: '/artisan-account',
  path: '/artisan-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContractsRoute = ApiContractsRouteImport.update({
  id: '/api-contracts',
  path: '/api-contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleRoute = AdminConsoleRouteImport.update({
  id: '/admin-console',
  path: '/admin-console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanIndexRoute = ArtisanIndexRouteImport.update({
  id: '/artisan/',
  path: '/artisan/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestIdRoute = RequestIdRouteImport.update({
  id: '/request/$id',
  path: '/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanIdRoute = ArtisanIdRouteImport.update({
  id: '/artisan/$id',
  path: '/artisan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-console': typeof AdminConsoleRoute
  '/api-contracts': typeof ApiContractsRoute
  '/architecture': typeof ArchitectureRoute
  '/artisan-account': typeof ArtisanAccountRoute
  '/dashboard': typeof DashboardRoute
  '/resident': typeof ResidentRoute
  '/resident-account': typeof ResidentAccountRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/request/$id': typeof RequestIdRoute
  '/artisan/': typeof ArtisanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-console': typeof AdminConsoleRoute
  '/api-contracts': typeof ApiContractsRoute
  '/architecture': typeof ArchitectureRoute
  '/artisan-account': typeof ArtisanAccountRoute
  '/dashboard': typeof DashboardRoute
  '/resident': typeof ResidentRoute
  '/resident-account': typeof ResidentAccountRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/request/$id': typeof RequestIdRoute
  '/artisan': typeof ArtisanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-console': typeof AdminConsoleRoute
  '/api-contracts': typeof ApiContractsRoute
  '/architecture': typeof ArchitectureRoute
  '/artisan-account': typeof ArtisanAccountRoute
  '/dashboard': typeof DashboardRoute
  '/resident': typeof ResidentRoute
  '/resident-account': typeof ResidentAccountRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/request/$id': typeof RequestIdRoute
  '/artisan/': typeof ArtisanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-console'
    | '/api-contracts'
    | '/architecture'
    | '/artisan-account'
    | '/dashboard'
    | '/resident'
    | '/resident-account'
    | '/sitemap.xml'
    | '/artisan/$id'
    | '/request/$id'
    | '/artisan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-console'
    | '/api-contracts'
    | '/architecture'
    | '/artisan-account'
    | '/dashboard'
    | '/resident'
    | '/resident-account'
    | '/sitemap.xml'
    | '/artisan/$id'
    | '/request/$id'
    | '/artisan'
  id:
    | '__root__'
    | '/'
    | '/admin-console'
    | '/api-contracts'
    | '/architecture'
    | '/artisan-account'
    | '/dashboard'
    | '/resident'
    | '/resident-account'
    | '/sitemap.xml'
    | '/artisan/$id'
    | '/request/$id'
    | '/artisan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminConsoleRoute: typeof AdminConsoleRoute
  ApiContractsRoute: typeof ApiContractsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ArtisanAccountRoute: typeof ArtisanAccountRoute
  DashboardRoute: typeof DashboardRoute
  ResidentRoute: typeof ResidentRoute
  ResidentAccountRoute: typeof ResidentAccountRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArtisanIdRoute: typeof ArtisanIdRoute
  RequestIdRoute: typeof RequestIdRoute
  ArtisanIndexRoute: typeof ArtisanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident-account': {
      id: '/resident-account'
      path: '/resident-account'
      fullPath: '/resident-account'
      preLoaderRoute: typeof ResidentAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident': {
      id: '/resident'
      path: '/resident'
      fullPath: '/resident'
      preLoaderRoute: typeof ResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan-account': {
      id: '/artisan-account'
      path: '/artisan-account'
      fullPath: '/artisan-account'
      preLoaderRoute: typeof ArtisanAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-contracts': {
      id: '/api-contracts'
      path: '/api-contracts'
      fullPath: '/api-contracts'
      preLoaderRoute: typeof ApiContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-console': {
      id: '/admin-console'
      path: '/admin-console'
      fullPath: '/admin-console'
      preLoaderRoute: typeof AdminConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/': {
      id: '/artisan/'
      path: '/artisan'
      fullPath: '/artisan/'
      preLoaderRoute: typeof ArtisanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$id': {
      id: '/request/$id'
      path: '/request/$id'
      fullPath: '/request/$id'
      preLoaderRoute: typeof RequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/$id': {
      id: '/artisan/$id'
      path: '/artisan/$id'
      fullPath: '/artisan/$id'
      preLoaderRoute: typeof ArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminConsoleRoute: AdminConsoleRoute,
  ApiContractsRoute: ApiContractsRoute,
  ArchitectureRoute: ArchitectureRoute,
  ArtisanAccountRoute: ArtisanAccountRoute,
  DashboardRoute: DashboardRoute,
  ResidentRoute: ResidentRoute,
  ResidentAccountRoute: ResidentAccountRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArtisanIdRoute: ArtisanIdRoute,
  RequestIdRoute: RequestIdRoute,
  ArtisanIndexRoute: ArtisanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
